name: Pull request check for tf-aws-infra repo
on:
  pull_request:
    branches:
      - main
jobs:
  terraform_pull_request_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform fmt
        working-directory: ./terraform
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        # working-directory: ./terraform
        run: terraform validate